# Generated by Django 5.2.4 on 2025-08-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
